<?php 

//Adds options pages
if( function_exists('acf_add_options_page') ) {
  
  acf_add_options_page(array(
    'page_title'  => __('Theme Settings', 'webnerds'),
    'menu_title'  => __('Theme Settings', 'webnerds'),
    'menu_slug'   => 'theme-general-settings',
    'capability'  => 'edit_posts',
    'redirect'    => false
  ));
  
  acf_add_options_sub_page(array(
    'page_title'  => 'Menus',
    'menu_title'  => 'Menus',
    'parent_slug' => 'theme-general-settings',
  ));

  acf_add_options_sub_page(array(
    'page_title'  => 'Theme Header Settings',
    'menu_title'  => 'Header',
    'parent_slug' => 'theme-general-settings',
  ));
  
  acf_add_options_sub_page(array(
    'page_title'  => 'Theme Footer Settings',
    'menu_title'  => 'Footer',
    'parent_slug' => 'theme-general-settings',
  ));

  acf_add_options_sub_page(array(
    'page_title'  => 'Technical Settings',
    'menu_title'  => 'Technical Settings',
    'parent_slug' => 'theme-general-settings',
  ));
}

if( function_exists('acf_add_local_field_group') ):

//menus
acf_add_local_field_group(array (
  'key' => 'group_57dfd7341ddda',
  'title' => 'Menus',
  'fields' => array (
    array (
      'key' => 'field_57dfd75f9aebb',
      'label' => __('Expanded menu', 'webnerds'),
      'name' => 'expanded_menu',
      'type' => 'repeater',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'collapsed' => '',
      'min' => '',
      'max' => '',
      'layout' => 'block',
      'button_label' => 'Add menu group',
      'sub_fields' => array (
        array (
          'key' => 'field_57dfd7ba9aebc',
          'label' => __('Title', 'webnerds'),
          'name' => 'title',
          'type' => 'text',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ),
        array (
          'key' => 'field_57dfd7db9aebd',
          'label' => __('Menu', 'webnerds'),
          'name' => 'menu',
          'type' => 'nav_menu',
          'instructions' => '',
          'required' => 1,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'save_format' => 'id',
          'container' => 0,
          'allow_null' => 0,
        ),
      ),
    ),
    array (
      'key' => 'field_57dfe0f6c84a2',
      'label' => __('Show expanded menu for', 'webnerds'),
      'name' => 'expanded_menu_show',
      'type' => 'checkbox',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'choices' => array (
        'desktop' => 'desktop',
        'mobile' => 'mobile',
      ),
      'default_value' => array (
      ),
      'layout' => 'horizontal',
      'toggle' => 0,
      'return_format' => 'value',
    ),
    array (
      'key' => 'field_57dfd9c62c864',
      'label' => __('Quick Menu', 'webnerds'),
      'name' => 'quick_menu',
      'type' => 'nav_menu',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'save_format' => 'id',
      'container' => 'nav',
      'allow_null' => 1,
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'options_page',
        'operator' => '==',
        'value' => 'acf-options-menus',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'seamless',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));


//contact info
  acf_add_local_field_group(array (
    'key' => 'group_571619652ee46',
    'title' => 'Contact Information',
    'fields' => array (
      array (
        'key' => 'field_57163f51c26e9',
        'label' => __('Company name', 'webnerds'),
        'name' => 'company_name',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
        'readonly' => 0,
        'disabled' => 0,
      ),
      array (
        'key' => 'field_57161c91061b0',
        'label' => __('Phone', 'webnerds'),
        'name' => 'company_phone',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
        'readonly' => 0,
        'disabled' => 0,
      ),
      array (
        'key' => 'field_57161d59061b1',
        'label' => __('Email', 'webnerds'),
        'name' => 'company_email',
        'type' => 'email',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array (
        'key' => 'field_57161e19061b2',
        'label' => __('Address', 'webnerds'),
        'name' => 'company_address',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
        'readonly' => 0,
        'disabled' => 0,
      ),
      array (
        'key' => 'field_57b5b3943348f',
        'label' => __('City', 'webnerds'),
        'name' => 'company_city',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
        'readonly' => 0,
        'disabled' => 0,
      ),
      array (
        'key' => 'field_57b5b39f33490',
        'label' => __('Zipcode', 'webnerds'),
        'name' => 'company_zip',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
        'readonly' => 0,
        'disabled' => 0,
      ),
    ),
    'location' => array (
      array (
        array (
          'param' => 'options_page',
          'operator' => '==',
          'value' => 'theme-general-settings',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
  ));

//Footer settings
  acf_add_local_field_group(array (
    'key' => 'group_57163c4f60bfb',
    'title' => 'Footer settings',
    'fields' => array (
      array (
        'key' => 'field_57163f7c0ddf4',
        'label' => __('Contact info', 'webnerds'),
        'name' => 'contact_info',
        'type' => 'textarea',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'maxlength' => '',
        'rows' => '',
        'new_lines' => 'br',
        'readonly' => 0,
        'disabled' => 0,
      ),
      array (
        'key' => 'field_571e0219cbdbc',
        'label' => __('Site info', 'webnerds'),
        'name' => 'site_info',
        'type' => 'page_link',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'post_type' => array (
          0 => 'page',
        ),
        'taxonomy' => array (
        ),
        'allow_null' => 0,
        'multiple' => 0,
        'allow_archives' => 1,
      ),
      array (
        'key' => 'field_57b2c146f3a6d',
        'label' => __('Footer extra', 'webnerds'),
        'name' => 'footer_extra',
        'type' => 'wysiwyg',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'tabs' => 'all',
        'toolbar' => 'basic',
        'media_upload' => 0,
      ),
    ),
    'location' => array (
      array (
        array (
          'param' => 'options_page',
          'operator' => '==',
          'value' => 'acf-options-footer',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
  ));

//Header CTA
  acf_add_local_field_group(array (
    'key' => 'group_572c6bf47633b',
    'title' => 'Header CTA',
    'fields' => array (
      array (
        'key' => 'field_572c6d44dde26',
        'label' => __('Show CTA', 'webnerds'),
        'name' => 'header_has_cta',
        'type' => 'true_false',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'message' => '',
        'default_value' => 0,
      ),
      array (
        'key' => 'field_572c6ccc4d49e',
        'label' => __('Title', 'webnerds'),
        'name' => 'header_cta_title',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => array (
          array (
            array (
              'field' => 'field_572c6d44dde26',
              'operator' => '==',
              'value' => '1',
            ),
          ),
        ),
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
        'readonly' => 0,
        'disabled' => 0,
      ),
      array (
        'key' => 'field_572c6d0b4d49f',
        'label' => __('Link', 'webnerds'),
        'name' => 'header_cta_link',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => array (
          array (
            array (
              'field' => 'field_572c6d44dde26',
              'operator' => '==',
              'value' => '1',
            ),
          ),
        ),
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
        'readonly' => 0,
        'disabled' => 0,
      ),
    ),
    'location' => array (
      array (
        array (
          'param' => 'options_page',
          'operator' => '==',
          'value' => 'acf-options-header',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
  ));

//logo
  acf_add_local_field_group(array (
    'key' => 'group_572c62687d6bf',
    'title' => 'Logo',
    'fields' => array (
      array (
        'key' => 'field_572c6395a748c',
        'label' => __('Dark logo', 'webnerds'),
        'name' => 'dark_logo',
        'type' => 'image',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'url',
        'preview_size' => 'thumbnail',
        'library' => 'all',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
      ),
      array (
        'key' => 'field_572c63e07e6e0',
        'label' => __('Light logo', 'webnerds'),
        'name' => 'light_logo',
        'type' => 'image',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'url',
        'preview_size' => 'thumbnail',
        'library' => 'all',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
      ),
    ),
    'location' => array (
      array (
        array (
          'param' => 'options_page',
          'operator' => '==',
          'value' => 'theme-general-settings',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
  ));

//Social Media
  acf_add_local_field_group(array (
    'key' => 'group_571a1ea261854',
    'title' => 'Social Media',
    'fields' => array (
      array (
        'key' => 'field_57161e3d061b3',
        'label' => __('Facebook', 'webnerds'),
        'name' => 'facebook',
        'type' => 'url',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
      ),
      array (
        'key' => 'field_57161e6a061b4',
        'label' => __('Instagram', 'webnerds'),
        'name' => 'instagram',
        'type' => 'url',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
      ),
      array (
        'key' => 'field_57161e85061b5',
        'label' => __('Youtube', 'webnerds'),
        'name' => 'youtube',
        'type' => 'url',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
      ),
    ),
    'location' => array (
      array (
        array (
          'param' => 'options_page',
          'operator' => '==',
          'value' => 'theme-general-settings',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
  ));

//Technical settings
  acf_add_local_field_group(array (
    'key' => 'group_571a1f4ac6b5d',
    'title' => 'Technical Settings',
    'fields' => array (
      array (
        'key' => 'field_571a1f8b5c6d4',
        'label' => __('Site info', 'webnerds'),
        'name' => 'site_info',
        'type' => 'page_link',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'post_type' => array (
          0 => 'page',
        ),
        'taxonomy' => array (
        ),
        'allow_null' => 0,
        'multiple' => 0,
        'allow_archives' => 1,
      ),
      array (
        'key' => 'facebook_pixel_571a1f8b5c6d4',
        'label' => __('Facebook Pixel', 'webnerds'),
        'name' => 'facebook_pixel',
        'type' => 'textarea',
        'instructions' => __('Paste your Facebook Pixel code here','webnerds'),
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'maxlength' => '',
        'rows' => '',
        'new_lines' => '',
        'readonly' => 0,
        'disabled' => 0,
      ),
      array (
        'key' => 'body_start_js_571a1f8b5c6d4',
        'label' => __('Body Start JS', 'webnerds'),
        'name' => 'body_start_js',
        'type' => 'textarea',
        'instructions' => __('Code added here is inserted right after the opening body tag. ','webnerds') . __('Include script tags.','webnerds') ,
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'maxlength' => '',
        'rows' => '',
        'new_lines' => '',
        'readonly' => 0,
        'disabled' => 0,
      ),
      array (
        'key' => 'body_end_js_571a1f8b5c6d4',
        'label' => __('Body End JS', 'webnerds'),
        'name' => 'body_end_js',
        'type' => 'textarea',
        'instructions' => __('Code added here is inserted right before the closing body tag.','webnerds') . __('Include script tags.','webnerds'),
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'maxlength' => '',
        'rows' => '',
        'new_lines' => '',
        'readonly' => 0,
        'disabled' => 0,
      ),
    ),
    'location' => array (
      array (
        array (
          'param' => 'options_page',
          'operator' => '==',
          'value' => 'acf-options-technical-settings',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
  ));
endif;